### DISCUSSION TITLE
What is the opposite status to "OK"?

### DISCUSSION THREAD

**Discussion by KDYR** [wmbusmeters/wmbusmeters#828] [General]
Some of the sensors created for my FlowIQ 2200 are binary and the status is reported as "OK" (leak, burst etc). I want to create Home Assistant alerts for when one of these is not OK, but what is the status reported via MQTT in such case? 
"NotOK"? "Not OK"? "Error"? - or something else?
```
alert:
  water_leak_alert:
    name: "Warning: Meter is indicating presence of a leak"
    entity_id: binary_sensor.watermeter_status_leak
    state: "XXX"
    repeat: 12
    can_acknowledge: true
    skip_first: false
```
Is there a way to test such alarms without throwing out a lot of water?
