### DISCUSSION TITLE
Can not get version 1.11.0-2  to work in home assistant.

### DISCUSSION THREAD

**Discussion by catdogmaus** [wmbusmeters/wmbusmeters#896] [Q&A] [answered]
The changelog says that HA implements the new format, but fails to specify what the changes in 1.11.0-2 actually are. I also looked at the docs as suggested, but I can't see anything that should actually be changed.
Attempt to start gives me simply  "Invalid dict for option 'conf' in Wmbusmeters (W-MBus to MQTT) (cada3e3b_wmbusmeters)." error.
My conf part in HA is an exact copy of docs suggested conf part!
The only difference I see is the data path, I have: /config/wmbusmeters but even when I change it to /etc/wmbusmeters.conf it is not possible to save it as option.
Maybe someone can specify what actually needs to be done to get this in HA to work.

**Comment by thecem** [comment]
Pls paste your config!

**Reply by catdogmaus** [reply]
For some unknown reason, I am not able to paste text as code here
At least in preview, it looks completely distorted. Because inserting code here is not possible, as a workaround I added txt file
[HA settings.txt](https://github.com/weetmuts/wmbusmeters/files/10880173/HA.settings.txt)

`data_path: /etc/wmbusmeters.conf
enable_mqtt_discovery: true
conf:
  loglevel: normal
  device: auto:t1
  donotprobe: /dev/ttyAMA0
  logtelegrams: false
  format: json
  logfile: /dev/stdout
  shell: /wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"
meters:
  - name: MyTapWater
    id: 
    key: 
    driver: multical21
mqtt:
  host: 
  port: 1883
  user: 
  password: `

**Reply by BIBOLV** [reply]
```
data_path: /etc/wmbusmeters.conf
enable_mqtt_discovery: true
conf:
  loglevel: normal
  device: auto:t1
  donotprobe: /dev/ttyAMA0
  logtelegrams: false
  format: json
  logfile: /dev/stdout
  shell: /wmbusmeters/mosquitto_pub.sh \"wmbusmeters/$METER_NAME\" \"$METER_JSON\"
meters:
  - name: MyTapWater
    id: someid
    key: NOKEY
    driver: multical21
mqtt: {}
```
Try following config

**Comment by catdogmaus** [comment]
Since this add-on is clearly not working for me after the upgrade, what is the easiest way to go back to the previous version. There is no option like HA directly.

**Comment by piasekps** [comment]
I have a very similar issue, here is my config file.
```yaml
data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf:
  loglevel: normal
  device: auto
  donotprobe: /dev/ttyAMA0
  logtelegrams: false
  ignoreduplicates: true
  #meterfiles: /config/wmbusmeters/logs/meter_readings
  #meterfilesaction: overwrite
  logfile: /dev/stdout
  # logfile: /config/wmbusmeters/logs/wmbusmeters.log
  format: json 
  #logtimestamps: always
  shell: /usr/bin/mosquitto_pub -h <ip> -u <user> -P <password> -t wmbusmeters/$METER_NAME -m "$METER_JSON"
meters:
  - name: meter-0001
    id: <id1>
    driver: apator162
    key: 00000000000000000000000000000000
  - name: meter-0002
    id: <id2>
    driver: apator162
    key: 00000000000000000000000000000000
  - name: meter-0003
    id: <id3>
    driver: apator162
    key: 00000000000000000000000000000000
  - name: meter-0004
    id: <id4>
    driver: apator162
    key: 00000000000000000000000000000000
mqtt: {}

```
What is wrong with this

**Reply by catdogmaus** [reply]
I think HA version is broken. For me, it refuses to work even when I click reset defaults.

**Reply by BIBOLV** [reply]
From docs - `If you only using numbers you have to use quotation marks!`, so try setting all key values in quotation marks.

**Comment by weetmuts** [comment, marked as answer]
Are you using the new ha-addon location? https://github.com/wmbusmeters/wmbusmeters-ha-addon
@BIBOLV

**Reply by catdogmaus** [reply]
I installed it probably in November or so as described in the help files. My add-on repositories say: https://github.com/weetmuts/wmbusmeters/
Is that wrong? When so what is the correct procedure to change?

**Reply by BIBOLV** [reply]
Migration procedure:

1.  Backup existing configs and uninstall wmbusmeters addon
2. Navigate to Supervisor > Add-on Store > Repositories
3. Remove https://github.com/weetmuts/wmbusmeters and add https://github.com/wmbusmeters/wmbusmeters-ha-addon
4. Navigate to Supervisor > Add-on Store and press "Ctrl+R" or reload page in other way
5. Install [edge] wmbusmeters addon
6.  Restore config

In upcoming weeks config interface will change from built-in to dedicated that will also require to backup and restore configs.

**Reply by catdogmaus** [reply]
HI. I installed the new version but no matter what I do the result on the settings page is "Failed to save add-on configuration, Invalid list for option 'meters' in [edge] Wmbusmeters (W-MBus to MQTT) (c8a990ad_wmbusmeters-ha-addon-edge)." I have a feeling that it has something to do with the storage rights in HA, because even if I try to save the default settings, the result is the same error.
When I go to file editor and /config/wmbusmeters/ I actually still have the correct settings from the previous install/try in /config/wmbusmeters/etc/wmbusmeters.d/meter-0001 and /config/wmbusmeters/etc/wmbusmeters.conf so it should actually read settings from there but instead it shows me default in the settings page

**Reply by thecem** [reply]
Your config is in the wrong format, pls change to the new one.

**Reply by catdogmaus** [reply]
When my configuration is in the wrong format it means that the default configuration in add-on must be in the wrong format bcs my configuration now is exactly as default. And I **don't** use only numbers! I have an alphanumerical key.
(for some inexplicable reason, it does not preserve the format of the code when I place it here so I cant show it correctly)

`data_path: /config/wmbusmeters
enable_mqtt_discovery: true
conf:
  loglevel: normal
  device: auto:t1
  donotprobe: /dev/ttyAMA0
  logtelegrams: false
  format: json
  logfile: /dev/stdout
  shell: /wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"
meters:
  name: MyTapWater
  driver: multical21
  id:
  key:
mqtt:
  host:
  port: 1883
  user:
  password:`

**Reply by thecem** [reply]
Paste the config with all values in YAML format:

```YAML
my config
With values
```

paste the config
mark the config
Press:
![CAA92C69-D551-4EAE-A955-70FC907EBBB2](https://user-images.githubusercontent.com/46648579/224236908-6f655543-34b0-4714-9b29-3a12744276cd.jpeg)
Write after the “ ```” “YAML”
It should look like:
![A41B3261-BDF9-4748-B5B5-A6AF94C2C392](https://user-images.githubusercontent.com/46648579/224237107-1254d826-e030-4515-8cba-47d96990b0c7.jpeg)


Otherwise we not able to help.

**Reply by catdogmaus** [reply]
As I described this before error appears even when I try to save the default settings - that means not touching anything!

Specifically, when I do not make any changes and try to save default settings the result is:
"Failed to save add-on configuration, Invalid list for option 'meters' in [edge] Wmbusmeters (W-MBus to MQTT) (c8a990ad_wmbusmeters-ha-addon-edge). Got {'data_path': '/config/wmbusmeters', 'enable_mqtt_discovery': False, 'conf': {'loglevel': 'normal', 'device': 'auto:t1', 'donotprobe': '/dev/ttyAMA0', 'logtelegrams': False, 'format': 'json', 'logfile': '/dev/stdout', 'shell': '/wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"'}, 'meters': {'name': 'ElectricityMeter', 'driver': 'amiplus', 'id': '12345678', 'key': 'DEADBEEF1337DEADBEEF1337DEADBEEF'}, 'mqtt': {}}"

as u can see my yaml is basically same and also gives as result same basic error
```
YAML
data_path: /config/wmbusmeters
enable_mqtt_discovery: true
conf:
  loglevel: normal
  device: auto:t1
  donotprobe: /dev/ttyAMA0
  logtelegrams: false
  format: json
  logfile: /dev/stdout
  shell: /wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"
meters:
  name: MyTapWater
  driver: multical21
  id: 12345678
  key: 1BBBBBBBB22222222222222DDDDDD000
mqtt:
  host: MQTTuser
  port: 1883
  user: mqttuser
  password: password
```

**Reply by tOOmki** [reply]
This is my default config, cant save.

**The configuration file is also not created**

[edge] Wmbusmeters (W-MBus to MQTT)
Current version: 1.11.0-5-3 

```YAML
data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf:
  loglevel: normal
  device: auto:t1
  donotprobe: /dev/ttyAMA0
  logtelegrams: false
  format: json
  logfile: /dev/stdout
  shell: /wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"
meters:
  name: ElectricityMeter
  driver: amiplus
  id: "12345678"
  key: DEADBEEF1337DEADBEEF1337DEADBEEF
mqtt: {}
```

**Reply by thecem** [reply]
@catdogmaus: As your log describes to many times: `Invalid list for option 'meters' `

@tOOmki: this Config should work:

```YAML
data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf:
  loglevel: normal
  device: auto:t1
  donotprobe: /dev/ttyAMA0
  logtelegrams: false
  format: json
  logfile: /dev/stdout
  shell: /wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"
meters:
  - name: ElectricityMeter
    driver: amiplus
    id: "12345678"
    key: DEADBEEF1337DEADBEEF1337DEADBEEF
mqtt: {}
```
Be aware of the minimal change before name with the hyphen!! The hyphen is here key for an array!
Test and let me know.

**Reply by tOOmki** [reply]
It works, thanks !

**Reply by thecem** [reply]
@catdogmaus: same to you

```YAML
data_path: /config/wmbusmeters
enable_mqtt_discovery: true
conf:
  loglevel: normal
  device: auto:t1
  donotprobe: /dev/ttyAMA0
  logtelegrams: false
  format: json
  logfile: /dev/stdout
  shell: /wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"
meters:
  - name: MyTapWater
    driver: multical21
    id: “12345678”
    key: 1BBBBBBBB22222222222222DDDDDD000
mqtt:
  host: MQTTuser
  port: 1883
  user: mqttuser
  password: password
```
