### ISSUE TITLE
nanoCUL-Device not recognized at startup of the container. Gets detected when container is restarted.

### ISSUE THREAD

**Issue by O491dogan** [wmbusmeters/wmbusmeters#1171]
### Type of request

Question

### OS version

LXC with Debian 12

### wmbusmeters version

latest - 06.02.2024

### Your message goes here

Hello everyone, 

I have a minor problem with the use of the docker image.
At first, I used the method to build from source inside a debian lxc and I managed to get it all working very good.

Then I wanted to give the docker image a try and it also works quite well except for the case, when the container is starting.
It doesn't recognize the nanoCul-Stick at first and outputs:

```
Expected cul on /dev/ttyUSB0 but did not find it! Ignoring tty!
No wmbus device detected, waiting for a device to be plugged in.
```

When I restart the wmbusmeters container in portainer, the stick is recognized and the listening starts as expected:
`Started config cul on /dev/ttyUSB0 listening on c1`

Does someone experience the same behavior and has a hint what the problem may be?

**My setup:**

Debian 12 in a non-privileged LXC on a Proxmox Host.
I have passed through the nanoCul-Stick successfully as it works with the wmbusmeters build from source and also when I restart the container after it has already started up.

My **wmbusmeters-config** in /opt/wmbusmeters/etc/wmbusmeters.conf looks like this:

```
loglevel=normal
device=/dev/ttyUSB0:cul:c1
logtelegrams=false
format=json
shell=/usr/bin/mosquitto_pub -h 192.168.xxx.xx -p 1883 -t wmbusmeters/$METER_ID/total -m "$METER_JSON"
```

The **docker compose** I have used looks like this (docker runs as root inside the lxc):

```
version: "2"
services:
  wmbusmeters:
    image: wmbusmeters/wmbusmeters
    container_name: wmbusmeters
    restart: always
    volumes:
      - /opt/wmbusmeters:/wmbusmeters_data
      - /etc/localtime:/etc/localtime:ro
      #- /dev/:/dev/                       # <-- passing /dev/:/dev/ instead of /dev/tty/USB0 results in the same behaviour
      - /dev/ttyUSB0:/dev/ttyUSB0
```
A delayed start of the lxc container did not change anything regarding this behaviour.

I can provide additional information if necessary and if someone tells me what to provide.

P.S.: Nice piece of software, thanks! :-)
