### ISSUE TITLE
Maddalena RADIO EVO wM-BUS Parser Bug

### ISSUE THREAD

**Issue by MichaelGrafnetter** [wmbusmeters/wmbusmeters#1276]
Hello, I found an interesting issue with the wmbusmeters evo868 data parser.

Sample data, retrieved from the [Maddalena RADIO EVO wM-BUS RADIO MODULE 868 MHz](https://www.maddalena.it/en/product/radio-evo/) water meter using [rtl_433](https://github.com/merbanan/rtl_433):

```yml
Telegram: ae4424349938022350077abf0000202f2f041390bd0000046d1428123504fd17000000000e78065811812300441351270000426cff2c840113a8ab000082016c1e34d3013b9f0500c4016d2d3217318104fd280182046c1e34840413a8ab0000c404136f890000840513dc680000c40513f04a00061351270000c406f18d138e05000084071318000000c407131800000084081318000000c40813180000008409131800000000000000000000
Driver: evo868
DecryptionKey: none
```

Result (reproducible with multiple water meters from the same manufacturer):
- Value `consumption_at_history_4_m3` contains bad data (100682.48 instead of a number between 10.0 and 20.0 in the above sample).
- Values `history_5_date`, `history_6_date`, `consumption_at_history_5_m3`, and `consumption_at_history_6_m3` are missing from the output.

The issue is also reproducible at [wmbusmeters.org](https://wmbusmeters.org/analyze/ae4424349938022350077abf0000202f2f041390bd0000046d1428123504fd17000000000e78065811812300441351270000426cff2c840113a8ab000082016c1e34d3013b9f0500c4016d2d3217318104fd280182046c1e34840413a8ab0000c404136f890000840513dc680000c40513f04a00061351270000c406f18d138e05000084071318000000c407131800000084081318000000c40813180000008409131800000000000000000000:evo868).
