### ISSUE TITLE
Device cul:c1 is not working

### ISSUE THREAD

**Issue by mwildbolz** [wmbusmeters/wmbusmeters#1282]
### Type of request

Bug

### OS version

Debian 11

### wmbusmeters version

1.16.1-18-gc1509f6

### Your message goes here

Hello!

After some time of working without problems, I suddenly get a timeout after a reset command leading to a not working state of wmbusmeters.
A restart of the container is not sufficient to restore operation. The CUL USB stick has to be removed and re-attached to the USB port. Afterwards, a container restart is needed.

My CUL stick is: nanoCUL USB Stick FTDI CC1101 868MHz FW 1.67 Knick-Antenne FHEM CUL 868
Meter is a Kamstrup FlowIQ 2200

Do you have any idea, what the problem could be? A docker-topic, or maybe wmbusmeters-topic, or a basic linux problem?
Time between failures is approx. some days to 20 days.

Logfile details as following:
```
(wmbus) reset completed /dev/ttyUSB0:cul[]
(wmbus) resetting /dev/ttyUSB0:cul[]
(wmbus) reset completed /dev/ttyUSB0:cul[]
(wmbus) resetting /dev/ttyUSB0:cul[]
(wmbus device) timeout request id 1
(cul) setting link mode(s) c1 is not supported for this cul device!
[ALARM SpecifiedDeviceNotFound] the device cul:c1 is not working
No wmbus device detected, waiting for a device to be plugged in.
[ALARM SpecifiedDeviceNotFound] the device cul:c1 is not working
[ALARM SpecifiedDeviceNotFound] the device cul:c1 is not working
[ALARM SpecifiedDeviceNotFound] the device cul:c1 is not working
[ALARM SpecifiedDeviceNotFound] the device cul:c1 is not working
[ALARM SpecifiedDeviceNotFound] the device cul:c1 is not working
[ALARM SpecifiedDeviceNotFound] the device cul:c1 is not working
No wmbus device detected, waiting for a device to be plugged in.
```

Docker-Compose File is:
```
version: "2"
services:
  wmbusmeters:
    image: wmbusmeters/wmbusmeters:latest
    container_name: wmbusmeters
    restart: always
    network_mode: host
    volumes:
      - ./config:/wmbusmeters_data
      - /etc/localtime:/etc/localtime:ro

    devices:
      - /dev/ttyUSBcul:/dev/ttyUSB0
```
