### ISSUE TITLE
mosquitto_sub in conf file

### ISSUE THREAD

**Issue by adamaltmejd** [wmbusmeters/wmbusmeters#1394]
### Type of request

Question

### OS version

Debian

### wmbusmeters version

latest

### Your message goes here

Using rtl_433 to publish (encrypted) water meter readings to MQTT and want to fetch these using mosquitto_sub as is described in the readme. The mosquitto_sub command works and I am able to decrypt the message manually, but am not getting it to work with a docker compose and .conf file. Setting device=hex:CMD() like below does not work, neither am I amble to get a "command:" working in the docker-compose. Any suggestions?

```
device='hex:CMD(/usr/bin/mosquitto_sub ... | tr -d "\n" )'
```

**Comment by adamaltmejd** [comment]
Managed to make it work changing the entrypoint. So my docker-compose config is:

```
wmbusmeters:
    image: wmbusmeters/wmbusmeters
    container_name: wmbusmeters
    restart: unless-stopped
    networks:
      - breven_net
    extra_hosts:
      - <mqtt_host>:172.28.0.1
    secrets:
      - wmbus_mqtt_password
      - watermeter_encryption_key
    environment:
      - TZ=${TIMEZONE}
      - MQTT_USER=watermeter
      - MQTT_PASSWORD=/run/secrets/wmbus_mqtt_password
      - METER_KEY=/run/secrets/watermeter_encryption_key
    volumes:
      - ./wmbusmeters:/wmbusmeters_data
      - /etc/localtime:/etc/localtime:ro
      - ./mosquitto/config/isrgrootx1.pem:/isrgrootx1.pem
    entrypoint: /wmbusmeters_data/start_wmbusmeters.sh
```

And then the new entrypoint script (`./wmbusmeters/start_wmbusmeters.sh`):

```
#!/bin/sh
/wmbusmeters/wmbusmeters \
    --donotprobe=all \
    --usestdoutforlogging \
    --ignoreduplicates=true \
    --shell='/usr/bin/mosquitto_pub -h <mqtt_host> -p 8883 --cafile /isrgrootx1.pem -u ${MQTT_USER} -P $(cat ${MQTT_PASSWORD}) -t wmbusmeters/$METER_NAME -m "$METER_JSON"' \
    --alarmshell='/usr/bin/mosquitto_pub -h <mqtt_host> -p 8883 --cafile /isrgrootx1.pem -u ${MQTT_USER} -P $(cat ${MQTT_PASSWORD}) -t wmbusmeters/$METER_NAME -m "$ALARM_TYPE $ALARM_MESSAGE"' \
    --alarmexpectedactivity="mon-sun(00-23)" \
    --alarmtimeout=3h \
    'hex:CMD(/usr/bin/mosquitto_sub -h <mqtt_host> -p 8883 --cafile /isrgrootx1.pem -u ${MQTT_USER} -P $(cat ${MQTT_PASSWORD}) -t rtl_433/57596857/data)' \
    BrevenTapWater multical21:c1 57596857 $(cat ${METER_KEY})
```
