### ISSUE TITLE
missing priviledge mode in docker-compose.yml documentation

### ISSUE THREAD

**Issue by hahasagined** [wmbusmeters/wmbusmeters#1459]
### Type of request

Bug

### OS version

-

### wmbusmeters version

-

### Your message goes here

I would like to open an issue regarding a documentation bug  at https://github.com/wmbusmeters/wmbusmeters/blob/master/docker/README.md 

documentation:
```
version: "2"
services:
  wmbusmeters:
    image: wmbusmeters/wmbusmeters
    container_name: wmbusmeters
    restart: always
    volumes:
      - /opt/wmbusmeters:/wmbusmeters_data
      - /etc/localtime:/etc/localtime:ro
      - /dev/:/dev/
```
      
that does not work if one uses RTLSDR dongles (as described a few lines before), what is needed is `privileded: true` like this:
    
```
version: "2"
services:
  wmbusmeters:
    image: wmbusmeters/wmbusmeters
    privileged: true
    container_name: wmbusmeters
    restart: always
    volumes:
      - /opt/wmbusmeters:/wmbusmeters_data
      - /etc/localtime:/etc/localtime:ro
      - /dev/:/dev/
```
      
  I think that would help a few people out in the future if this could be added to the docker-compose.yml. 
  thanks
